/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData home = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData apartment = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData store = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData cart = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData phone_handset = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData map = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData gift = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData diamond = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData dinner = const IconData(0xe847, fontFamily: _kFontFam);
  static const IconData coffee_cup = const IconData(0xe848, fontFamily: _kFontFam);
  static const IconData leaf = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData earth = const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData alarm = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData mic = const IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData thumbs_up = const IconData(0xe86d, fontFamily: _kFontFam);
  static const IconData thumbs_down = const IconData(0xe86e, fontFamily: _kFontFam);
  static const IconData magnifier = const IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData cross = const IconData(0xe870, fontFamily: _kFontFam);
  static const IconData chevron_up = const IconData(0xe873, fontFamily: _kFontFam);
  static const IconData chevron_down = const IconData(0xe874, fontFamily: _kFontFam);
  static const IconData chevron_left = const IconData(0xe875, fontFamily: _kFontFam);
  static const IconData chevron_right = const IconData(0xe876, fontFamily: _kFontFam);
  static const IconData arrow_up = const IconData(0xe877, fontFamily: _kFontFam);
  static const IconData checkmark_cicle = const IconData(0xe87f, fontFamily: _kFontFam);
  static const IconData cross_circle = const IconData(0xe880, fontFamily: _kFontFam);
  static const IconData plus_circle = const IconData(0xe881, fontFamily: _kFontFam);
  static const IconData circle_minus = const IconData(0xe882, fontFamily: _kFontFam);
  static const IconData arrow_up_circle = const IconData(0xe883, fontFamily: _kFontFam);
  static const IconData arrow_down_circle = const IconData(0xe884, fontFamily: _kFontFam);
  static const IconData arrow_left_circle = const IconData(0xe885, fontFamily: _kFontFam);
  static const IconData arrow_right_circle = const IconData(0xe886, fontFamily: _kFontFam);
  static const IconData chevron_up_circle = const IconData(0xe887, fontFamily: _kFontFam);
  static const IconData chevron_down_circle = const IconData(0xe888, fontFamily: _kFontFam);
  static const IconData chevron_left_circle = const IconData(0xe889, fontFamily: _kFontFam);
  static const IconData chevron_right_circle = const IconData(0xe88a, fontFamily: _kFontFam);
}
